-- Guest invite list seed (42 guests)
INSERT INTO guests (name, name_key) VALUES ('Jimmy', 'jimmy');
INSERT INTO guests (name, name_key) VALUES ('Phi', 'phi');
INSERT INTO guests (name, name_key) VALUES ('Kate', 'kate');
INSERT INTO guests (name, name_key) VALUES ('William', 'william');
INSERT INTO guests (name, name_key) VALUES ('Sine', 'sine');
INSERT INTO guests (name, name_key) VALUES ('Harry', 'harry');
INSERT INTO guests (name, name_key) VALUES ('Harley', 'harley');
INSERT INTO guests (name, name_key) VALUES ('John', 'john');
INSERT INTO guests (name, name_key) VALUES ('Ananya', 'ananya');
INSERT INTO guests (name, name_key) VALUES ('Ben N', 'ben n');
INSERT INTO guests (name, name_key) VALUES ('Renie', 'renie');
INSERT INTO guests (name, name_key) VALUES ('Mo Lindz', 'mo lindz');
INSERT INTO guests (name, name_key) VALUES ('Audrey', 'audrey');
INSERT INTO guests (name, name_key) VALUES ('Ben H', 'ben h');
INSERT INTO guests (name, name_key) VALUES ('Lily Mannion', 'lily mannion');
INSERT INTO guests (name, name_key) VALUES ('Ailee', 'ailee');
INSERT INTO guests (name, name_key) VALUES ('Maley', 'maley');
INSERT INTO guests (name, name_key) VALUES ('Sachin', 'sachin');
INSERT INTO guests (name, name_key) VALUES ('Claudia', 'claudia');
INSERT INTO guests (name, name_key) VALUES ('Kwesi', 'kwesi');
INSERT INTO guests (name, name_key) VALUES ('Slay', 'slay');
INSERT INTO guests (name, name_key) VALUES ('Annalise', 'annalise');
INSERT INTO guests (name, name_key) VALUES ('Drew', 'drew');
INSERT INTO guests (name, name_key) VALUES ('A-Pop', 'a-pop');
INSERT INTO guests (name, name_key) VALUES ('Armaan', 'armaan');
INSERT INTO guests (name, name_key) VALUES ('Seve', 'seve');
INSERT INTO guests (name, name_key) VALUES ('Erin', 'erin');
INSERT INTO guests (name, name_key) VALUES ('Mike', 'mike');
INSERT INTO guests (name, name_key) VALUES ('Mandy', 'mandy');
INSERT INTO guests (name, name_key) VALUES ('Anthony', 'anthony');
INSERT INTO guests (name, name_key) VALUES ('Sam', 'sam');
INSERT INTO guests (name, name_key) VALUES ('Arthi', 'arthi');
INSERT INTO guests (name, name_key) VALUES ('Arjun', 'arjun');
INSERT INTO guests (name, name_key) VALUES ('Haley', 'haley');
INSERT INTO guests (name, name_key) VALUES ('Rachel', 'rachel');
INSERT INTO guests (name, name_key) VALUES ('Arnav', 'arnav');
INSERT INTO guests (name, name_key) VALUES ('Dani', 'dani');
INSERT INTO guests (name, name_key) VALUES ('Katrina', 'katrina');
INSERT INTO guests (name, name_key) VALUES ('Mary', 'mary');
INSERT INTO guests (name, name_key) VALUES ('Nicole', 'nicole');
INSERT INTO guests (name, name_key) VALUES ('Sonia', 'sonia');
INSERT INTO guests (name, name_key) VALUES ('Chels', 'chels');
