# Generated by Django 3.0.8 on 2020-07-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screener',
            name='id',
        ),
        migrations.AlterField(
            model_name='screener',
            name='full_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='screener',
            name='short_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
