# Generated by Django 3.0.8 on 2020-07-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_auto_20200712_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='screener',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screener',
            name='short_name',
            field=models.CharField(max_length=100),
        ),
    ]
